#!/usr/bin/env ruby

require File.expand_path('../lib/patronize.rb', File.dirname(__FILE__))
require 'mercenary'

def sanitize_options(options)
  options["address"].gsub!(/_/, ',').gsub!(/\+/, ' ')
  options
end

Mercenary.program(:new) do |n|
  n.syntax "script/new <city> [options]"

  n.option 'name', '-n', '--name NAME', 'The name of the establishment'
  n.option 'marker', '-m', '--marker SYMBOL', 'The marker symbol for the establishment'
  n.option 'address', '-a', '--address ADDR', 'The address of the establishment'

  n.option 'city', '-c', '--city CITY', 'The city to add this establishment to'
  n.option 'lat', '-L', '--lat COORD', 'The latitude of the establishment'
  n.option 'lon', '-l', '--lon COORD', 'The longitude of the establishment'

  n.action do |args, options|
    city = options.fetch('city')
    add_feature_to_city city, sanitize_options(options)
  end
end
